name: Output information
on: workflow_dispatch

jobs:
  info: 
    runs-on: ubuntu-latest
    
    steps:
        - name: Output Message 
          run: echo "Testing a output ...."

        - name: Output GitHub context
          run: echo "${{ toJSON(github) }}"